site_name: Open Topo Data
site_url: https://www.opentopodata.org
site_description: Open DEM server.

theme:
    name: 'material'

repo_name: ajnisbet/opentopodata
repo_url: https://github.com/ajnisbet/opentopodata
google_analytics: ['UA-59478184-7', 'www.opentopodata.org']

extra_javascript:
  - 'point-query.js'

nav:
    - Introduction: 'index.md'
    - Server docs: 'server.md'
    - API docs: 'api.md'

markdown_extensions:
  - admonition
  - markdown.extensions.codehilite:
      guess_lang: false