site_name: Open Topo Data
site_url: https://www.opentopodata.org
site_description: Open DEM server.

theme:
    name: 'material'

repo_name: ajnisbet/opentopodata
repo_url: https://github.com/ajnisbet/opentopodata
google_analytics: ['UA-59478184-7', 'www.opentopodata.org']

nav:
    - Introduction: 'index.md'
    - Server docs: 'server.md'
    - API docs: 'api.md'
    - Datasets:
      - ETOPO1: 'datasets/etopo1.md'
      - EU-DEM: 'datasets/eudem.md'
      - SRTM (30m): 'datasets/srtm30.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition