site_name: Open Topo Data
site_url: https://www.opentopodata.org
site_description: Open DEM server.

theme:
    name: 'material'

repo_name: ajnisbet/opentopodata
repo_url: https://github.com/ajnisbet/opentopodata
google_analytics: ['UA-59478184-7', 'www.opentopodata.org']

nav:
    - Introduction: 'index.md'
    - Server docs: 'server.md'
    - API docs: 'api.md'
    - Release notes: 'changelog.md'
    - Datasets:
      - ASTER: 'datasets/aster.md'
      - ETOPO1: 'datasets/etopo1.md'
      - EU-DEM: 'datasets/eudem.md'
      - SRTM: 'datasets/srtm.md'
      - NED: 'datasets/ned.md'
      - EMOD Bathymetry: 'datasets/emod2018.md'
      - GEBCO Bathymetry: 'datasets/gebco2020.md'

extra_javascript:
  - js/extra.js

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition